In [8]:
import numpy as np
import matplotlib 

In [10]:
a= np.array([[1,2,3,4],[6,7,8,9]])
a

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [13]:
a.shape

(2, 4)

In [14]:
a[0]

array([1, 2, 3, 4])

In [15]:
a[1]

array([6, 7, 8, 9])

In [18]:
a[1,2]

8

In [19]:
import random

In [20]:
prob=random.random()

In [21]:
prob

0.12434374034169549

In [22]:
value=random.randint(1,3)

In [23]:
value

2

In [24]:
import numpy as np

In [32]:
np.random.randint(1,6,(6,3))

array([[1, 2, 4],
       [3, 5, 2],
       [4, 2, 1],
       [3, 5, 4],
       [1, 1, 5],
       [3, 3, 2]])